package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Caracteristicasproducto generated by hbm2java
 */
@Entity
@Table(name = "caracteristicasproducto", schema = "web")
public class Caracteristicasproducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7781794727370547521L;
	private int idcaracteristicasproducto;
	private Producto producto;
	private String descripcion;
	private byte[] imagen;

	public Caracteristicasproducto() {
	}

	public Caracteristicasproducto(int idcaracteristicasproducto,
			Producto producto, String descripcion) {
		this.idcaracteristicasproducto = idcaracteristicasproducto;
		this.producto = producto;
		this.descripcion = descripcion;
	}

	public Caracteristicasproducto(int idcaracteristicasproducto,
			Producto producto, String descripcion, byte[] imagen) {
		this.idcaracteristicasproducto = idcaracteristicasproducto;
		this.producto = producto;
		this.descripcion = descripcion;
		this.imagen = imagen;
	}

	@Id
	@Column(name = "idcaracteristicasproducto", unique = true, nullable = false)
	public int getIdcaracteristicasproducto() {
		return this.idcaracteristicasproducto;
	}

	public void setIdcaracteristicasproducto(int idcaracteristicasproducto) {
		this.idcaracteristicasproducto = idcaracteristicasproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "imagen")
	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

}
