package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", schema = "web")
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2928448399227707236L;
	private int idcliente;
	private Set<?> personas = new HashSet<Object>(0);
	private Set<?> listadeseos = new HashSet<Object>(0);
	private Set<?> formapagoClientes = new HashSet<Object>(0);
	private Set<?> revisionproductos = new HashSet<Object>(0);
	private Set<?> carritocompras = new HashSet<Object>(0);
	private Set<?> pedidos = new HashSet<Object>(0);
	private Set<?> facturas = new HashSet<Object>(0);
	private Set<?> revisionproveedors = new HashSet<Object>(0);
	private Set<?> empresas = new HashSet<Object>(0);
	private Set<?> direccionclientes = new HashSet<Object>(0);

	public Cliente() {
	}

	public Cliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public Cliente(int idcliente, Set<?> personas, Set<?> listadeseos,
			Set<?> formapagoClientes, Set<?> revisionproductos, Set<?> carritocompras,
			Set<?> pedidos, Set<?> facturas, Set<?> revisionproveedors, Set<?> empresas,
			Set<?> direccionclientes) {
		this.idcliente = idcliente;
		this.personas = personas;
		this.listadeseos = listadeseos;
		this.formapagoClientes = formapagoClientes;
		this.revisionproductos = revisionproductos;
		this.carritocompras = carritocompras;
		this.pedidos = pedidos;
		this.facturas = facturas;
		this.revisionproveedors = revisionproveedors;
		this.empresas = empresas;
		this.direccionclientes = direccionclientes;
	}

	@Id
	@Column(name = "idcliente", unique = true, nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<?> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<?> personas) {
		this.personas = personas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<?> getListadeseos() {
		return this.listadeseos;
	}

	public void setListadeseos(Set<?> listadeseos) {
		this.listadeseos = listadeseos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<?> getFormapagoClientes() {
		return this.formapagoClientes;
	}

	public void setFormapagoClientes(Set<?> formapagoClientes) {
		this.formapagoClientes = formapagoClientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<?> getRevisionproductos() {
		return this.revisionproductos;
	}

	public void setRevisionproductos(Set<?> revisionproductos) {
		this.revisionproductos = revisionproductos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<?> getCarritocompras() {
		return this.carritocompras;
	}

	public void setCarritocompras(Set<?> carritocompras) {
		this.carritocompras = carritocompras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<?> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<?> pedidos) {
		this.pedidos = pedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<?> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<?> facturas) {
		this.facturas = facturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<?> getRevisionproveedors() {
		return this.revisionproveedors;
	}

	public void setRevisionproveedors(Set<?> revisionproveedors) {
		this.revisionproveedors = revisionproveedors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<?> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<?> empresas) {
		this.empresas = empresas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<?> getDireccionclientes() {
		return this.direccionclientes;
	}

	public void setDireccionclientes(Set<?> direccionclientes) {
		this.direccionclientes = direccionclientes;
	}

}
