package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name = "cuenta", schema = "web", uniqueConstraints = {
		@UniqueConstraint(columnNames = "numero"),
		@UniqueConstraint(columnNames = "codigo") })
public class Cuenta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -426852923533253897L;
	private int idcuenta;
	private Grupocuenta grupocuenta;
	private short numero;
	private String codigo;
	private String descripcion;
	private Set<?> contabilidads = new HashSet<Object>(0);

	public Cuenta() {
	}

	public Cuenta(int idcuenta, Grupocuenta grupocuenta, short numero,
			String codigo) {
		this.idcuenta = idcuenta;
		this.grupocuenta = grupocuenta;
		this.numero = numero;
		this.codigo = codigo;
	}

	public Cuenta(int idcuenta, Grupocuenta grupocuenta, short numero,
			String codigo, String descripcion, Set<?> contabilidads) {
		this.idcuenta = idcuenta;
		this.grupocuenta = grupocuenta;
		this.numero = numero;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.contabilidads = contabilidads;
	}

	@Id
	@Column(name = "idcuenta", unique = true, nullable = false)
	public int getIdcuenta() {
		return this.idcuenta;
	}

	public void setIdcuenta(int idcuenta) {
		this.idcuenta = idcuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idgrupocuenta", nullable = false)
	public Grupocuenta getGrupocuenta() {
		return this.grupocuenta;
	}

	public void setGrupocuenta(Grupocuenta grupocuenta) {
		this.grupocuenta = grupocuenta;
	}

	@Column(name = "numero", unique = true, nullable = false)
	public short getNumero() {
		return this.numero;
	}

	public void setNumero(short numero) {
		this.numero = numero;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuenta")
	public Set<?> getContabilidads() {
		return this.contabilidads;
	}

	public void setContabilidads(Set<?> contabilidads) {
		this.contabilidads = contabilidads;
	}

}
