package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Descripcionproducto generated by hbm2java
 */
@Entity
@Table(name = "descripcionproducto", schema = "web")
public class Descripcionproducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1075629957707319563L;
	private int iddescripcionproducto;
	private Producto producto;
	private String descripcion;

	public Descripcionproducto() {
	}

	public Descripcionproducto(int iddescripcionproducto, Producto producto,
			String descripcion) {
		this.iddescripcionproducto = iddescripcionproducto;
		this.producto = producto;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "iddescripcionproducto", unique = true, nullable = false)
	public int getIddescripcionproducto() {
		return this.iddescripcionproducto;
	}

	public void setIddescripcionproducto(int iddescripcionproducto) {
		this.iddescripcionproducto = iddescripcionproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
