package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalletecnicoproducto generated by hbm2java
 */
@Entity
@Table(name = "detalletecnicoproducto", schema = "web")
public class Detalletecnicoproducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6527797061271166856L;
	private int iddetalletecnicoproducto;
	private Producto producto;
	private String descripcion;
	private byte[] imagen;

	public Detalletecnicoproducto() {
	}

	public Detalletecnicoproducto(int iddetalletecnicoproducto,
			Producto producto, String descripcion) {
		this.iddetalletecnicoproducto = iddetalletecnicoproducto;
		this.producto = producto;
		this.descripcion = descripcion;
	}

	public Detalletecnicoproducto(int iddetalletecnicoproducto,
			Producto producto, String descripcion, byte[] imagen) {
		this.iddetalletecnicoproducto = iddetalletecnicoproducto;
		this.producto = producto;
		this.descripcion = descripcion;
		this.imagen = imagen;
	}

	@Id
	@Column(name = "iddetalletecnicoproducto", unique = true, nullable = false)
	public int getIddetalletecnicoproducto() {
		return this.iddetalletecnicoproducto;
	}

	public void setIddetalletecnicoproducto(int iddetalletecnicoproducto) {
		this.iddetalletecnicoproducto = iddetalletecnicoproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "descripcion", nullable = false, length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "imagen")
	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

}
