package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Detallefactura generated by hbm2java
 */
@Entity
@Table(name = "detallefactura", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = "iddetallepedido"))
public class Detallefactura implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2051393129650083078L;
	private int iddetallefactura;
	private Factura factura;
	private Statusdetallefactura statusdetallefactura;
	private Detallepedido detallepedido;
	private Set<?> detalleenvios = new HashSet<Object>(0);

	public Detallefactura() {
	}

	public Detallefactura(int iddetallefactura, Factura factura,
			Statusdetallefactura statusdetallefactura,
			Detallepedido detallepedido) {
		this.iddetallefactura = iddetallefactura;
		this.factura = factura;
		this.statusdetallefactura = statusdetallefactura;
		this.detallepedido = detallepedido;
	}

	public Detallefactura(int iddetallefactura, Factura factura,
			Statusdetallefactura statusdetallefactura,
			Detallepedido detallepedido, Set<?> detalleenvios) {
		this.iddetallefactura = iddetallefactura;
		this.factura = factura;
		this.statusdetallefactura = statusdetallefactura;
		this.detallepedido = detallepedido;
		this.detalleenvios = detalleenvios;
	}

	@Id
	@Column(name = "iddetallefactura", unique = true, nullable = false)
	public int getIddetallefactura() {
		return this.iddetallefactura;
	}

	public void setIddetallefactura(int iddetallefactura) {
		this.iddetallefactura = iddetallefactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfactura", nullable = false)
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idstatusdetallefactura", nullable = false)
	public Statusdetallefactura getStatusdetallefactura() {
		return this.statusdetallefactura;
	}

	public void setStatusdetallefactura(
			Statusdetallefactura statusdetallefactura) {
		this.statusdetallefactura = statusdetallefactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddetallepedido", unique = true, nullable = false)
	public Detallepedido getDetallepedido() {
		return this.detallepedido;
	}

	public void setDetallepedido(Detallepedido detallepedido) {
		this.detallepedido = detallepedido;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detallefactura")
	public Set<?> getDetalleenvios() {
		return this.detalleenvios;
	}

	public void setDetalleenvios(Set<?> detalleenvios) {
		this.detalleenvios = detalleenvios;
	}

}
