package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Detalleenvio generated by hbm2java
 */
@Entity
@Table(name = "detalleenvio", schema = "web", uniqueConstraints = {
		@UniqueConstraint(columnNames = "iddetallefactura"),
		@UniqueConstraint(columnNames = "iddetallepedido") })
public class Detalleenvio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4171464733685094911L;
	private int iddetalleenvio;
	private Statusdetallepedido statusdetallepedido;
	private Envio envio;
	private Detallefactura detallefactura;
	private Detallepedido detallepedido;

	public Detalleenvio() {
	}

	public Detalleenvio(int iddetalleenvio,
			Statusdetallepedido statusdetallepedido, Envio envio,
			Detallefactura detallefactura, Detallepedido detallepedido) {
		this.iddetalleenvio = iddetalleenvio;
		this.statusdetallepedido = statusdetallepedido;
		this.envio = envio;
		this.detallefactura = detallefactura;
		this.detallepedido = detallepedido;
	}

	@Id
	@Column(name = "iddetalleenvio", unique = true, nullable = false)
	public int getIddetalleenvio() {
		return this.iddetalleenvio;
	}

	public void setIddetalleenvio(int iddetalleenvio) {
		this.iddetalleenvio = iddetalleenvio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idstatusdetalleenvio", nullable = false)
	public Statusdetallepedido getStatusdetallepedido() {
		return this.statusdetallepedido;
	}

	public void setStatusdetallepedido(Statusdetallepedido statusdetallepedido) {
		this.statusdetallepedido = statusdetallepedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idenvio", nullable = false)
	public Envio getEnvio() {
		return this.envio;
	}

	public void setEnvio(Envio envio) {
		this.envio = envio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddetallefactura", unique = true, nullable = false)
	public Detallefactura getDetallefactura() {
		return this.detallefactura;
	}

	public void setDetallefactura(Detallefactura detallefactura) {
		this.detallefactura = detallefactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddetallepedido", unique = true, nullable = false)
	public Detallepedido getDetallepedido() {
		return this.detallepedido;
	}

	public void setDetallepedido(Detallepedido detallepedido) {
		this.detallepedido = detallepedido;
	}

}
