package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Direccioncliente generated by hbm2java
 */
@Entity
@Table(name = "direccioncliente", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = {
		"pais", "estadoprovincia", "ciudad" }))
public class Direccioncliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2326280428341386374L;
	private int iddireccioncliente;
	private Ciudad ciudad;
	private Cliente cliente;
	private String nombre;
	private String pais;
	private String estadoprovincia;
	private String ciudad_1;
	private String direccion1;
	private String direccion2;
	private String telefono;
	private String celular;
	private String codigopostal;
	private String codigoseguridadacceso;
	private Set<?> formapagoClientes = new HashSet<Object>(0);
	private Set<?> pedidos = new HashSet<Object>(0);
	private Set<?> facturas = new HashSet<Object>(0);
	private Set<?> envios = new HashSet<Object>(0);

	public Direccioncliente() {
	}

	public Direccioncliente(int iddireccioncliente, Ciudad ciudad,
			Cliente cliente, String nombre, String pais,
			String estadoprovincia, String ciudad_1, String direccion1,
			String telefono) {
		this.iddireccioncliente = iddireccioncliente;
		this.ciudad = ciudad;
		this.cliente = cliente;
		this.nombre = nombre;
		this.pais = pais;
		this.estadoprovincia = estadoprovincia;
		this.ciudad_1 = ciudad_1;
		this.direccion1 = direccion1;
		this.telefono = telefono;
	}

	public Direccioncliente(int iddireccioncliente, Ciudad ciudad,
			Cliente cliente, String nombre, String pais,
			String estadoprovincia, String ciudad_1, String direccion1,
			String direccion2, String telefono, String celular,
			String codigopostal, String codigoseguridadacceso,
			Set<?> formapagoClientes, Set<?> pedidos, Set<?> facturas, Set<?> envios) {
		this.iddireccioncliente = iddireccioncliente;
		this.ciudad = ciudad;
		this.cliente = cliente;
		this.nombre = nombre;
		this.pais = pais;
		this.estadoprovincia = estadoprovincia;
		this.ciudad_1 = ciudad_1;
		this.direccion1 = direccion1;
		this.direccion2 = direccion2;
		this.telefono = telefono;
		this.celular = celular;
		this.codigopostal = codigopostal;
		this.codigoseguridadacceso = codigoseguridadacceso;
		this.formapagoClientes = formapagoClientes;
		this.pedidos = pedidos;
		this.facturas = facturas;
		this.envios = envios;
	}

	@Id
	@Column(name = "iddireccioncliente", unique = true, nullable = false)
	public int getIddireccioncliente() {
		return this.iddireccioncliente;
	}

	public void setIddireccioncliente(int iddireccioncliente) {
		this.iddireccioncliente = iddireccioncliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idciudad", nullable = false)
	public Ciudad getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "pais", nullable = false, length = 50)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "estadoprovincia", nullable = false, length = 50)
	public String getEstadoprovincia() {
		return this.estadoprovincia;
	}

	public void setEstadoprovincia(String estadoprovincia) {
		this.estadoprovincia = estadoprovincia;
	}

	@Column(name = "ciudad", nullable = false, length = 50)
	public String getCiudad_1() {
		return this.ciudad_1;
	}

	public void setCiudad_1(String ciudad_1) {
		this.ciudad_1 = ciudad_1;
	}

	@Column(name = "direccion1", nullable = false, length = 100)
	public String getDireccion1() {
		return this.direccion1;
	}

	public void setDireccion1(String direccion1) {
		this.direccion1 = direccion1;
	}

	@Column(name = "direccion2", length = 100)
	public String getDireccion2() {
		return this.direccion2;
	}

	public void setDireccion2(String direccion2) {
		this.direccion2 = direccion2;
	}

	@Column(name = "telefono", nullable = false, length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "celular", length = 15)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "codigopostal", length = 15)
	public String getCodigopostal() {
		return this.codigopostal;
	}

	public void setCodigopostal(String codigopostal) {
		this.codigopostal = codigopostal;
	}

	@Column(name = "codigoseguridadacceso", length = 15)
	public String getCodigoseguridadacceso() {
		return this.codigoseguridadacceso;
	}

	public void setCodigoseguridadacceso(String codigoseguridadacceso) {
		this.codigoseguridadacceso = codigoseguridadacceso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccioncliente")
	public Set<?> getFormapagoClientes() {
		return this.formapagoClientes;
	}

	public void setFormapagoClientes(Set<?> formapagoClientes) {
		this.formapagoClientes = formapagoClientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccioncliente")
	public Set<?> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<?> pedidos) {
		this.pedidos = pedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccioncliente")
	public Set<?> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<?> facturas) {
		this.facturas = facturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccioncliente")
	public Set<?> getEnvios() {
		return this.envios;
	}

	public void setEnvios(Set<?> envios) {
		this.envios = envios;
	}

}
