package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", schema = "web", uniqueConstraints = {
		@UniqueConstraint(columnNames = "ruc"),
		@UniqueConstraint(columnNames = "idlogin"),
		@UniqueConstraint(columnNames = "idproveedor"),
		@UniqueConstraint(columnNames = "idcliente") })
public class Empresa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8338589347437365039L;
	private int idempresa;
	private Proveedor proveedor;
	private Login login;
	private Cliente cliente;
	private String ruc;
	private String nombrecomercial;
	private String razonsocial;
	private String sitioweb;
	private Set<?> transaccioncontables = new HashSet<Object>(0);

	public Empresa() {
	}

	public Empresa(int idempresa, Login login, String ruc,
			String nombrecomercial, String razonsocial) {
		this.idempresa = idempresa;
		this.login = login;
		this.ruc = ruc;
		this.nombrecomercial = nombrecomercial;
		this.razonsocial = razonsocial;
	}

	public Empresa(int idempresa, Proveedor proveedor, Login login,
			Cliente cliente, String ruc, String nombrecomercial,
			String razonsocial, String sitioweb, Set<?> transaccioncontables) {
		this.idempresa = idempresa;
		this.proveedor = proveedor;
		this.login = login;
		this.cliente = cliente;
		this.ruc = ruc;
		this.nombrecomercial = nombrecomercial;
		this.razonsocial = razonsocial;
		this.sitioweb = sitioweb;
		this.transaccioncontables = transaccioncontables;
	}

	@Id
	@Column(name = "idempresa", unique = true, nullable = false)
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproveedor", unique = true)
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idlogin", unique = true, nullable = false)
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente", unique = true)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "ruc", unique = true, nullable = false, length = 20)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@Column(name = "nombrecomercial", nullable = false, length = 50)
	public String getNombrecomercial() {
		return this.nombrecomercial;
	}

	public void setNombrecomercial(String nombrecomercial) {
		this.nombrecomercial = nombrecomercial;
	}

	@Column(name = "razonsocial", nullable = false, length = 50)
	public String getRazonsocial() {
		return this.razonsocial;
	}

	public void setRazonsocial(String razonsocial) {
		this.razonsocial = razonsocial;
	}

	@Column(name = "sitioweb", length = 20)
	public String getSitioweb() {
		return this.sitioweb;
	}

	public void setSitioweb(String sitioweb) {
		this.sitioweb = sitioweb;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getTransaccioncontables() {
		return this.transaccioncontables;
	}

	public void setTransaccioncontables(Set<?> transaccioncontables) {
		this.transaccioncontables = transaccioncontables;
	}

}
