package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Envio generated by hbm2java
 */
@Entity
@Table(name = "envio", schema = "web")
public class Envio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2708001984135556638L;
	private int idenvio;
	private Proveedor proveedor;
	private Statusenvio statusenvio;
	private Factura factura;
	private Direccioncliente direccioncliente;
	private Pedido pedido;
	private Metodoenvio metodoenvio;
	private String numerotracking;
	private Date fechaenvio;
	private String transportista;
	private Date fechaentrega;
	private String personarecibe;
	private Set<?> detalleenvios = new HashSet<Object>(0);
	private Set<?> envioStatusenvios = new HashSet<Object>(0);

	public Envio() {
	}

	public Envio(int idenvio, Proveedor proveedor, Statusenvio statusenvio,
			Factura factura, Direccioncliente direccioncliente, Pedido pedido,
			Metodoenvio metodoenvio, String numerotracking, Date fechaenvio,
			String transportista) {
		this.idenvio = idenvio;
		this.proveedor = proveedor;
		this.statusenvio = statusenvio;
		this.factura = factura;
		this.direccioncliente = direccioncliente;
		this.pedido = pedido;
		this.metodoenvio = metodoenvio;
		this.numerotracking = numerotracking;
		this.fechaenvio = fechaenvio;
		this.transportista = transportista;
	}

	public Envio(int idenvio, Proveedor proveedor, Statusenvio statusenvio,
			Factura factura, Direccioncliente direccioncliente, Pedido pedido,
			Metodoenvio metodoenvio, String numerotracking, Date fechaenvio,
			String transportista, Date fechaentrega, String personarecibe,
			Set<?> detalleenvios, Set<?> envioStatusenvios) {
		this.idenvio = idenvio;
		this.proveedor = proveedor;
		this.statusenvio = statusenvio;
		this.factura = factura;
		this.direccioncliente = direccioncliente;
		this.pedido = pedido;
		this.metodoenvio = metodoenvio;
		this.numerotracking = numerotracking;
		this.fechaenvio = fechaenvio;
		this.transportista = transportista;
		this.fechaentrega = fechaentrega;
		this.personarecibe = personarecibe;
		this.detalleenvios = detalleenvios;
		this.envioStatusenvios = envioStatusenvios;
	}

	@Id
	@Column(name = "idenvio", unique = true, nullable = false)
	public int getIdenvio() {
		return this.idenvio;
	}

	public void setIdenvio(int idenvio) {
		this.idenvio = idenvio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproveedor", nullable = false)
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idstatusenvio", nullable = false)
	public Statusenvio getStatusenvio() {
		return this.statusenvio;
	}

	public void setStatusenvio(Statusenvio statusenvio) {
		this.statusenvio = statusenvio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfactura", nullable = false)
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddireccioncliente", nullable = false)
	public Direccioncliente getDireccioncliente() {
		return this.direccioncliente;
	}

	public void setDireccioncliente(Direccioncliente direccioncliente) {
		this.direccioncliente = direccioncliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpedido", nullable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmetodoenvio", nullable = false)
	public Metodoenvio getMetodoenvio() {
		return this.metodoenvio;
	}

	public void setMetodoenvio(Metodoenvio metodoenvio) {
		this.metodoenvio = metodoenvio;
	}

	@Column(name = "numerotracking", nullable = false, length = 20)
	public String getNumerotracking() {
		return this.numerotracking;
	}

	public void setNumerotracking(String numerotracking) {
		this.numerotracking = numerotracking;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaenvio", nullable = false, length = 29)
	public Date getFechaenvio() {
		return this.fechaenvio;
	}

	public void setFechaenvio(Date fechaenvio) {
		this.fechaenvio = fechaenvio;
	}

	@Column(name = "transportista", nullable = false, length = 50)
	public String getTransportista() {
		return this.transportista;
	}

	public void setTransportista(String transportista) {
		this.transportista = transportista;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaentrega", length = 29)
	public Date getFechaentrega() {
		return this.fechaentrega;
	}

	public void setFechaentrega(Date fechaentrega) {
		this.fechaentrega = fechaentrega;
	}

	@Column(name = "personarecibe", length = 50)
	public String getPersonarecibe() {
		return this.personarecibe;
	}

	public void setPersonarecibe(String personarecibe) {
		this.personarecibe = personarecibe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "envio")
	public Set<?> getDetalleenvios() {
		return this.detalleenvios;
	}

	public void setDetalleenvios(Set<?> detalleenvios) {
		this.detalleenvios = detalleenvios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "envio")
	public Set<?> getEnvioStatusenvios() {
		return this.envioStatusenvios;
	}

	public void setEnvioStatusenvios(Set<?> envioStatusenvios) {
		this.envioStatusenvios = envioStatusenvios;
	}

}
