package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EnvioStatusenvio generated by hbm2java
 */
@Entity
@Table(name = "envio_statusenvio", schema = "web")
public class EnvioStatusenvio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6228044744642625104L;
	private int idenvioStatusenvio;
	private Statusenvio statusenvio;
	private Envio envio;
	private Date fecha;
	private String comentarios;

	public EnvioStatusenvio() {
	}

	public EnvioStatusenvio(int idenvioStatusenvio, Statusenvio statusenvio,
			Envio envio, Date fecha) {
		this.idenvioStatusenvio = idenvioStatusenvio;
		this.statusenvio = statusenvio;
		this.envio = envio;
		this.fecha = fecha;
	}

	public EnvioStatusenvio(int idenvioStatusenvio, Statusenvio statusenvio,
			Envio envio, Date fecha, String comentarios) {
		this.idenvioStatusenvio = idenvioStatusenvio;
		this.statusenvio = statusenvio;
		this.envio = envio;
		this.fecha = fecha;
		this.comentarios = comentarios;
	}

	@Id
	@Column(name = "idenvio_statusenvio", unique = true, nullable = false)
	public int getIdenvioStatusenvio() {
		return this.idenvioStatusenvio;
	}

	public void setIdenvioStatusenvio(int idenvioStatusenvio) {
		this.idenvioStatusenvio = idenvioStatusenvio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idstatusenvio", nullable = false)
	public Statusenvio getStatusenvio() {
		return this.statusenvio;
	}

	public void setStatusenvio(Statusenvio statusenvio) {
		this.statusenvio = statusenvio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idenvio", nullable = false)
	public Envio getEnvio() {
		return this.envio;
	}

	public void setEnvio(Envio envio) {
		this.envio = envio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "comentarios", length = 500)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

}
