package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadoprovincia generated by hbm2java
 */
@Entity
@Table(name = "estadoprovincia", schema = "web")
public class Estadoprovincia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1803512152600490917L;
	private int idestadoprovincia;
	private Pais pais;
	private String nombre;
	private String descripcion;
	private Set<?> ciudads = new HashSet<Object>(0);

	public Estadoprovincia() {
	}

	public Estadoprovincia(int idestadoprovincia, Pais pais, String nombre) {
		this.idestadoprovincia = idestadoprovincia;
		this.pais = pais;
		this.nombre = nombre;
	}

	public Estadoprovincia(int idestadoprovincia, Pais pais, String nombre,
			String descripcion, Set<?> ciudads) {
		this.idestadoprovincia = idestadoprovincia;
		this.pais = pais;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.ciudads = ciudads;
	}

	@Id
	@Column(name = "idestadoprovincia", unique = true, nullable = false)
	public int getIdestadoprovincia() {
		return this.idestadoprovincia;
	}

	public void setIdestadoprovincia(int idestadoprovincia) {
		this.idestadoprovincia = idestadoprovincia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpais", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoprovincia")
	public Set<?> getCiudads() {
		return this.ciudads;
	}

	public void setCiudads(Set<?> ciudads) {
		this.ciudads = ciudads;
	}

}
