package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FacturaStatusfactura generated by hbm2java
 */
@Entity
@Table(name = "factura_statusfactura", schema = "web")
public class FacturaStatusfactura implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8220359996217987649L;
	private int idfacturaStatusfactura;
	private Statusfactura statusfactura;
	private Factura factura;
	private Date fecha;
	private String comentarios;

	public FacturaStatusfactura() {
	}

	public FacturaStatusfactura(int idfacturaStatusfactura,
			Statusfactura statusfactura, Factura factura, Date fecha) {
		this.idfacturaStatusfactura = idfacturaStatusfactura;
		this.statusfactura = statusfactura;
		this.factura = factura;
		this.fecha = fecha;
	}

	public FacturaStatusfactura(int idfacturaStatusfactura,
			Statusfactura statusfactura, Factura factura, Date fecha,
			String comentarios) {
		this.idfacturaStatusfactura = idfacturaStatusfactura;
		this.statusfactura = statusfactura;
		this.factura = factura;
		this.fecha = fecha;
		this.comentarios = comentarios;
	}

	@Id
	@Column(name = "idfactura_statusfactura", unique = true, nullable = false)
	public int getIdfacturaStatusfactura() {
		return this.idfacturaStatusfactura;
	}

	public void setIdfacturaStatusfactura(int idfacturaStatusfactura) {
		this.idfacturaStatusfactura = idfacturaStatusfactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idstatusfactura", nullable = false)
	public Statusfactura getStatusfactura() {
		return this.statusfactura;
	}

	public void setStatusfactura(Statusfactura statusfactura) {
		this.statusfactura = statusfactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfactura", nullable = false)
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "comentarios", length = 500)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

}
