package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * FormapagoCliente generated by hbm2java
 */
@Entity
@Table(name = "formapago_cliente", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = "iddireccioncliente"))
public class FormapagoCliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -331070754970413574L;
	private int idformapagoCliente;
	private Formapago formapago;
	private Direccioncliente direccioncliente;
	private Cliente cliente;
	private String numero;
	private String nombre;
	private Date fechaexpiracion;
	private Set<?> pagos = new HashSet<Object>(0);

	public FormapagoCliente() {
	}

	public FormapagoCliente(int idformapagoCliente, Formapago formapago,
			Direccioncliente direccioncliente, Cliente cliente, String numero,
			String nombre, Date fechaexpiracion) {
		this.idformapagoCliente = idformapagoCliente;
		this.formapago = formapago;
		this.direccioncliente = direccioncliente;
		this.cliente = cliente;
		this.numero = numero;
		this.nombre = nombre;
		this.fechaexpiracion = fechaexpiracion;
	}

	public FormapagoCliente(int idformapagoCliente, Formapago formapago,
			Direccioncliente direccioncliente, Cliente cliente, String numero,
			String nombre, Date fechaexpiracion, Set<?> pagos) {
		this.idformapagoCliente = idformapagoCliente;
		this.formapago = formapago;
		this.direccioncliente = direccioncliente;
		this.cliente = cliente;
		this.numero = numero;
		this.nombre = nombre;
		this.fechaexpiracion = fechaexpiracion;
		this.pagos = pagos;
	}

	@Id
	@Column(name = "idformapago_cliente", unique = true, nullable = false)
	public int getIdformapagoCliente() {
		return this.idformapagoCliente;
	}

	public void setIdformapagoCliente(int idformapagoCliente) {
		this.idformapagoCliente = idformapagoCliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idformapago", nullable = false)
	public Formapago getFormapago() {
		return this.formapago;
	}

	public void setFormapago(Formapago formapago) {
		this.formapago = formapago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddireccioncliente", unique = true, nullable = false)
	public Direccioncliente getDireccioncliente() {
		return this.direccioncliente;
	}

	public void setDireccioncliente(Direccioncliente direccioncliente) {
		this.direccioncliente = direccioncliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "numero", nullable = false, length = 20)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaexpiracion", nullable = false, length = 13)
	public Date getFechaexpiracion() {
		return this.fechaexpiracion;
	}

	public void setFechaexpiracion(Date fechaexpiracion) {
		this.fechaexpiracion = fechaexpiracion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagoCliente")
	public Set<?> getPagos() {
		return this.pagos;
	}

	public void setPagos(Set<?> pagos) {
		this.pagos = pagos;
	}

}
