package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Grupocuenta generated by hbm2java
 */
@Entity
@Table(name = "grupocuenta", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Grupocuenta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4596669172833979564L;
	private int idgrupocuenta;
	private String codigo;
	private String descripcion;
	private short primernumerocuenta;
	private short ultimonumerocuenta;
	private Set<?> cuentas = new HashSet<Object>(0);

	public Grupocuenta() {
	}

	public Grupocuenta(int idgrupocuenta, String codigo,
			short primernumerocuenta, short ultimonumerocuenta) {
		this.idgrupocuenta = idgrupocuenta;
		this.codigo = codigo;
		this.primernumerocuenta = primernumerocuenta;
		this.ultimonumerocuenta = ultimonumerocuenta;
	}

	public Grupocuenta(int idgrupocuenta, String codigo, String descripcion,
			short primernumerocuenta, short ultimonumerocuenta, Set<?> cuentas) {
		this.idgrupocuenta = idgrupocuenta;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.primernumerocuenta = primernumerocuenta;
		this.ultimonumerocuenta = ultimonumerocuenta;
		this.cuentas = cuentas;
	}

	@Id
	@Column(name = "idgrupocuenta", unique = true, nullable = false)
	public int getIdgrupocuenta() {
		return this.idgrupocuenta;
	}

	public void setIdgrupocuenta(int idgrupocuenta) {
		this.idgrupocuenta = idgrupocuenta;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "primernumerocuenta", nullable = false)
	public short getPrimernumerocuenta() {
		return this.primernumerocuenta;
	}

	public void setPrimernumerocuenta(short primernumerocuenta) {
		this.primernumerocuenta = primernumerocuenta;
	}

	@Column(name = "ultimonumerocuenta", nullable = false)
	public short getUltimonumerocuenta() {
		return this.ultimonumerocuenta;
	}

	public void setUltimonumerocuenta(short ultimonumerocuenta) {
		this.ultimonumerocuenta = ultimonumerocuenta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupocuenta")
	public Set<?> getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set<?> cuentas) {
		this.cuentas = cuentas;
	}

}
