package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ListadeseoProducto generated by hbm2java
 */
@Entity
@Table(name = "listadeseo_producto", schema = "web")
public class ListadeseoProducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6290985938648061972L;
	private int idlistadeseoProducto;
	private Listadeseo listadeseo;
	private Prioridad prioridad;
	private Producto producto;
	private double precioreferencia;
	private Date fechaagregado;

	public ListadeseoProducto() {
	}

	public ListadeseoProducto(int idlistadeseoProducto, Listadeseo listadeseo,
			Prioridad prioridad, Producto producto, double precioreferencia) {
		this.idlistadeseoProducto = idlistadeseoProducto;
		this.listadeseo = listadeseo;
		this.prioridad = prioridad;
		this.producto = producto;
		this.precioreferencia = precioreferencia;
	}

	public ListadeseoProducto(int idlistadeseoProducto, Listadeseo listadeseo,
			Prioridad prioridad, Producto producto, double precioreferencia,
			Date fechaagregado) {
		this.idlistadeseoProducto = idlistadeseoProducto;
		this.listadeseo = listadeseo;
		this.prioridad = prioridad;
		this.producto = producto;
		this.precioreferencia = precioreferencia;
		this.fechaagregado = fechaagregado;
	}

	@Id
	@Column(name = "idlistadeseo_producto", unique = true, nullable = false)
	public int getIdlistadeseoProducto() {
		return this.idlistadeseoProducto;
	}

	public void setIdlistadeseoProducto(int idlistadeseoProducto) {
		this.idlistadeseoProducto = idlistadeseoProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idlistadeseo", nullable = false)
	public Listadeseo getListadeseo() {
		return this.listadeseo;
	}

	public void setListadeseo(Listadeseo listadeseo) {
		this.listadeseo = listadeseo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idprioridad", nullable = false)
	public Prioridad getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Prioridad prioridad) {
		this.prioridad = prioridad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "precioreferencia", nullable = false, scale = 0)
	public double getPrecioreferencia() {
		return this.precioreferencia;
	}

	public void setPrecioreferencia(double precioreferencia) {
		this.precioreferencia = precioreferencia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaagregado", length = 13)
	public Date getFechaagregado() {
		return this.fechaagregado;
	}

	public void setFechaagregado(Date fechaagregado) {
		this.fechaagregado = fechaagregado;
	}

}
