package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Listadeseo generated by hbm2java
 */
@Entity
@Table(name = "listadeseo", schema = "web")
public class Listadeseo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5316533378505788931L;
	private int idlistadeseo;
	private Cliente cliente;
	private String nombre;
	private Date fechacreacion;
	private String email;
	private Set<?> listadeseoProductos = new HashSet<Object>(0);

	public Listadeseo() {
	}

	public Listadeseo(int idlistadeseo, Cliente cliente, String nombre,
			Date fechacreacion) {
		this.idlistadeseo = idlistadeseo;
		this.cliente = cliente;
		this.nombre = nombre;
		this.fechacreacion = fechacreacion;
	}

	public Listadeseo(int idlistadeseo, Cliente cliente, String nombre,
			Date fechacreacion, String email, Set<?> listadeseoProductos) {
		this.idlistadeseo = idlistadeseo;
		this.cliente = cliente;
		this.nombre = nombre;
		this.fechacreacion = fechacreacion;
		this.email = email;
		this.listadeseoProductos = listadeseoProductos;
	}

	@Id
	@Column(name = "idlistadeseo", unique = true, nullable = false)
	public int getIdlistadeseo() {
		return this.idlistadeseo;
	}

	public void setIdlistadeseo(int idlistadeseo) {
		this.idlistadeseo = idlistadeseo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "nombre", nullable = false, length = 10)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacreacion", nullable = false, length = 13)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "email", length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listadeseo")
	public Set<?> getListadeseoProductos() {
		return this.listadeseoProductos;
	}

	public void setListadeseoProductos(Set<?> listadeseoProductos) {
		this.listadeseoProductos = listadeseoProductos;
	}

}
