package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "marca", schema = "web")
public class Marca implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -688864814418563035L;
	private int idmarca;
	private Pais pais;
	private String nombre;
	private Set<?> productos = new HashSet<Object>(0);

	public Marca() {
	}

	public Marca(int idmarca, Pais pais, String nombre) {
		this.idmarca = idmarca;
		this.pais = pais;
		this.nombre = nombre;
	}

	public Marca(int idmarca, Pais pais, String nombre, Set<?> productos) {
		this.idmarca = idmarca;
		this.pais = pais;
		this.nombre = nombre;
		this.productos = productos;
	}

	@Id
	@Column(name = "idmarca", unique = true, nullable = false)
	public int getIdmarca() {
		return this.idmarca;
	}

	public void setIdmarca(int idmarca) {
		this.idmarca = idmarca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpais", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@Column(name = "nombre", nullable = false, length = 10)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<?> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<?> productos) {
		this.productos = productos;
	}

}
