package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ofertaespecial generated by hbm2java
 */
@Entity
@Table(name = "ofertaespecial", schema = "web")
public class Ofertaespecial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5300395039597757633L;
	private int idofertaespecial;
	private ProductoProveedor productoProveedor;
	private Date fechainicio;
	private Date fechafin;
	private Double valordescuento;
	private String descripcion;
	private byte[] imagen;
	private String terminoscondiciones;
	private Set<?> pedidoOfertaespecials = new HashSet<Object>(0);

	public Ofertaespecial() {
	}

	public Ofertaespecial(int idofertaespecial,
			ProductoProveedor productoProveedor, Date fechainicio,
			Date fechafin, String descripcion) {
		this.idofertaespecial = idofertaespecial;
		this.productoProveedor = productoProveedor;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.descripcion = descripcion;
	}

	public Ofertaespecial(int idofertaespecial,
			ProductoProveedor productoProveedor, Date fechainicio,
			Date fechafin, Double valordescuento, String descripcion,
			byte[] imagen, String terminoscondiciones, Set<?> pedidoOfertaespecials) {
		this.idofertaespecial = idofertaespecial;
		this.productoProveedor = productoProveedor;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.valordescuento = valordescuento;
		this.descripcion = descripcion;
		this.imagen = imagen;
		this.terminoscondiciones = terminoscondiciones;
		this.pedidoOfertaespecials = pedidoOfertaespecials;
	}

	@Id
	@Column(name = "idofertaespecial", unique = true, nullable = false)
	public int getIdofertaespecial() {
		return this.idofertaespecial;
	}

	public void setIdofertaespecial(int idofertaespecial) {
		this.idofertaespecial = idofertaespecial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto_proveedor", nullable = false)
	public ProductoProveedor getProductoProveedor() {
		return this.productoProveedor;
	}

	public void setProductoProveedor(ProductoProveedor productoProveedor) {
		this.productoProveedor = productoProveedor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechainicio", nullable = false, length = 13)
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechafin", nullable = false, length = 13)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	@Column(name = "valordescuento", scale = 0)
	public Double getValordescuento() {
		return this.valordescuento;
	}

	public void setValordescuento(Double valordescuento) {
		this.valordescuento = valordescuento;
	}

	@Column(name = "descripcion", nullable = false, length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "imagen")
	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	@Column(name = "terminoscondiciones")
	public String getTerminoscondiciones() {
		return this.terminoscondiciones;
	}

	public void setTerminoscondiciones(String terminoscondiciones) {
		this.terminoscondiciones = terminoscondiciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ofertaespecial")
	public Set<?> getPedidoOfertaespecials() {
		return this.pedidoOfertaespecials;
	}

	public void setPedidoOfertaespecials(Set<?> pedidoOfertaespecials) {
		this.pedidoOfertaespecials = pedidoOfertaespecials;
	}

}
