package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PagoStatuspago generated by hbm2java
 */
@Entity
@Table(name = "pago_statuspago", schema = "web")
public class PagoStatuspago implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7596035045571079660L;
	private int idpagoStatuspago;
	private Pago pago;
	private Statuspago statuspago;
	private Date fecha;
	private String comentarios;

	public PagoStatuspago() {
	}

	public PagoStatuspago(int idpagoStatuspago, Pago pago,
			Statuspago statuspago, Date fecha) {
		this.idpagoStatuspago = idpagoStatuspago;
		this.pago = pago;
		this.statuspago = statuspago;
		this.fecha = fecha;
	}

	public PagoStatuspago(int idpagoStatuspago, Pago pago,
			Statuspago statuspago, Date fecha, String comentarios) {
		this.idpagoStatuspago = idpagoStatuspago;
		this.pago = pago;
		this.statuspago = statuspago;
		this.fecha = fecha;
		this.comentarios = comentarios;
	}

	@Id
	@Column(name = "idpago_statuspago", unique = true, nullable = false)
	public int getIdpagoStatuspago() {
		return this.idpagoStatuspago;
	}

	public void setIdpagoStatuspago(int idpagoStatuspago) {
		this.idpagoStatuspago = idpagoStatuspago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpago", nullable = false)
	public Pago getPago() {
		return this.pago;
	}

	public void setPago(Pago pago) {
		this.pago = pago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idstatuspago", nullable = false)
	public Statuspago getStatuspago() {
		return this.statuspago;
	}

	public void setStatuspago(Statuspago statuspago) {
		this.statuspago = statuspago;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "comentarios", length = 500)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

}
