package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Pais implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 38210936135817670L;
	private int idpais;
	private String nombre;
	private String descripcion;
	private Set<?> estadoprovincias = new HashSet<Object>(0);
	private Set<?> marcas = new HashSet<Object>(0);

	public Pais() {
	}

	public Pais(int idpais, String nombre) {
		this.idpais = idpais;
		this.nombre = nombre;
	}

	public Pais(int idpais, String nombre, String descripcion,
			Set<?> estadoprovincias, Set<?> marcas) {
		this.idpais = idpais;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estadoprovincias = estadoprovincias;
		this.marcas = marcas;
	}

	@Id
	@Column(name = "idpais", unique = true, nullable = false)
	public int getIdpais() {
		return this.idpais;
	}

	public void setIdpais(int idpais) {
		this.idpais = idpais;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<?> getEstadoprovincias() {
		return this.estadoprovincias;
	}

	public void setEstadoprovincias(Set<?> estadoprovincias) {
		this.estadoprovincias = estadoprovincias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<?> getMarcas() {
		return this.marcas;
	}

	public void setMarcas(Set<?> marcas) {
		this.marcas = marcas;
	}

}
