package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", schema = "web")
public class Pedido implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1801042686487173149L;
	private int idpedido;
	private Statuspedido statuspedido;
	private Direccioncliente direccioncliente;
	private Cliente cliente;
	private String numeropedido;
	private Date fecha;
	private double valor;
	private double descuento;
	private double envio;
	private double subtotal;
	private double iva;
	private double total;
	private Set<?> envios = new HashSet<Object>(0);
	private Set<?> pedidoStatuspedidos = new HashSet<Object>(0);
	private Set<?> pagos = new HashSet<Object>(0);
	private Set<?> pedidoOfertaespecials = new HashSet<Object>(0);
	private Set<?> detallepedidos = new HashSet<Object>(0);
	private Set<?> facturas = new HashSet<Object>(0);

	public Pedido() {
	}

	public Pedido(int idpedido, Statuspedido statuspedido, Cliente cliente,
			String numeropedido, Date fecha, double valor, double descuento,
			double envio, double subtotal, double iva, double total) {
		this.idpedido = idpedido;
		this.statuspedido = statuspedido;
		this.cliente = cliente;
		this.numeropedido = numeropedido;
		this.fecha = fecha;
		this.valor = valor;
		this.descuento = descuento;
		this.envio = envio;
		this.subtotal = subtotal;
		this.iva = iva;
		this.total = total;
	}

	public Pedido(int idpedido, Statuspedido statuspedido,
			Direccioncliente direccioncliente, Cliente cliente,
			String numeropedido, Date fecha, double valor, double descuento,
			double envio, double subtotal, double iva, double total,
			Set<?> envios, Set<?> pedidoStatuspedidos, Set<?> pagos,
			Set<?> pedidoOfertaespecials, Set<?> detallepedidos, Set<?> facturas) {
		this.idpedido = idpedido;
		this.statuspedido = statuspedido;
		this.direccioncliente = direccioncliente;
		this.cliente = cliente;
		this.numeropedido = numeropedido;
		this.fecha = fecha;
		this.valor = valor;
		this.descuento = descuento;
		this.envio = envio;
		this.subtotal = subtotal;
		this.iva = iva;
		this.total = total;
		this.envios = envios;
		this.pedidoStatuspedidos = pedidoStatuspedidos;
		this.pagos = pagos;
		this.pedidoOfertaespecials = pedidoOfertaespecials;
		this.detallepedidos = detallepedidos;
		this.facturas = facturas;
	}

	@Id
	@Column(name = "idpedido", unique = true, nullable = false)
	public int getIdpedido() {
		return this.idpedido;
	}

	public void setIdpedido(int idpedido) {
		this.idpedido = idpedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idstatuspedido", nullable = false)
	public Statuspedido getStatuspedido() {
		return this.statuspedido;
	}

	public void setStatuspedido(Statuspedido statuspedido) {
		this.statuspedido = statuspedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddireccioncliente")
	public Direccioncliente getDireccioncliente() {
		return this.direccioncliente;
	}

	public void setDireccioncliente(Direccioncliente direccioncliente) {
		this.direccioncliente = direccioncliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "numeropedido", nullable = false, length = 20)
	public String getNumeropedido() {
		return this.numeropedido;
	}

	public void setNumeropedido(String numeropedido) {
		this.numeropedido = numeropedido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "valor", nullable = false, scale = 0)
	public double getValor() {
		return this.valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

	@Column(name = "descuento", nullable = false, scale = 0)
	public double getDescuento() {
		return this.descuento;
	}

	public void setDescuento(double descuento) {
		this.descuento = descuento;
	}

	@Column(name = "envio", nullable = false, scale = 0)
	public double getEnvio() {
		return this.envio;
	}

	public void setEnvio(double envio) {
		this.envio = envio;
	}

	@Column(name = "subtotal", nullable = false, scale = 0)
	public double getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(double subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "iva", nullable = false, scale = 0)
	public double getIva() {
		return this.iva;
	}

	public void setIva(double iva) {
		this.iva = iva;
	}

	@Column(name = "total", nullable = false, scale = 0)
	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<?> getEnvios() {
		return this.envios;
	}

	public void setEnvios(Set<?> envios) {
		this.envios = envios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<?> getPedidoStatuspedidos() {
		return this.pedidoStatuspedidos;
	}

	public void setPedidoStatuspedidos(Set<?> pedidoStatuspedidos) {
		this.pedidoStatuspedidos = pedidoStatuspedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<?> getPagos() {
		return this.pagos;
	}

	public void setPagos(Set<?> pagos) {
		this.pagos = pagos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<?> getPedidoOfertaespecials() {
		return this.pedidoOfertaespecials;
	}

	public void setPedidoOfertaespecials(Set<?> pedidoOfertaespecials) {
		this.pedidoOfertaespecials = pedidoOfertaespecials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<?> getDetallepedidos() {
		return this.detallepedidos;
	}

	public void setDetallepedidos(Set<?> detallepedidos) {
		this.detallepedidos = detallepedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<?> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<?> facturas) {
		this.facturas = facturas;
	}

}
