package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Prioridad generated by hbm2java
 */
@Entity
@Table(name = "prioridad", schema = "web")
public class Prioridad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6079617922466464586L;
	private int idprioridad;
	private String nombre;
	private Set<?> listadeseoProductos = new HashSet<Object>(0);

	public Prioridad() {
	}

	public Prioridad(int idprioridad, String nombre) {
		this.idprioridad = idprioridad;
		this.nombre = nombre;
	}

	public Prioridad(int idprioridad, String nombre, Set<?> listadeseoProductos) {
		this.idprioridad = idprioridad;
		this.nombre = nombre;
		this.listadeseoProductos = listadeseoProductos;
	}

	@Id
	@Column(name = "idprioridad", unique = true, nullable = false)
	public int getIdprioridad() {
		return this.idprioridad;
	}

	public void setIdprioridad(int idprioridad) {
		this.idprioridad = idprioridad;
	}

	@Column(name = "nombre", nullable = false, length = 10)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prioridad")
	public Set<?> getListadeseoProductos() {
		return this.listadeseoProductos;
	}

	public void setListadeseoProductos(Set<?> listadeseoProductos) {
		this.listadeseoProductos = listadeseoProductos;
	}

}
