package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", schema = "web")
public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4898477921552415967L;
	private int idproducto;
	private Tipoproducto tipoproducto;
	private Marca marca;
	private String nombre;
	private String modelo;
	private String serie;
	private String descripcion;
	private short calificacion;
	private int likes;
	private double preciominimo;
	private short stock;
	private Date fechapublicacion;
	private BigDecimal alto;
	private BigDecimal ancho;
	private BigDecimal profundidad;
	private BigDecimal peso;
	private BigDecimal pesoenvio;
	private String envio;
	private Set<?> productoTamanios = new HashSet<Object>(0);
	private Set<?> productorelacionados = new HashSet<Object>(0);
	private Set<?> productoMaterials = new HashSet<Object>(0);
	private Set<?> productoCondicions = new HashSet<Object>(0);
	private Set<?> revisionproductos = new HashSet<Object>(0);
	private Set<?> listadeseoProductos = new HashSet<Object>(0);
	private Set<?> descripcionproductos = new HashSet<Object>(0);
	private Set<?> productoProveedors = new HashSet<Object>(0);
	private Set<?> carritocompras = new HashSet<Object>(0);
	private Set<?> imagenproductos = new HashSet<Object>(0);
	private Set<?> detalletecnicoproductos = new HashSet<Object>(0);
	private Set<?> caracteristicasproductos = new HashSet<Object>(0);
	private Set<?> productoColors = new HashSet<Object>(0);

	public Producto() {
	}

	public Producto(int idproducto, Tipoproducto tipoproducto, Marca marca,
			String nombre, String modelo, String serie, String descripcion,
			short calificacion, int likes, double preciominimo, short stock,
			Date fechapublicacion, BigDecimal alto, BigDecimal ancho,
			BigDecimal profundidad, BigDecimal peso, BigDecimal pesoenvio,
			String envio) {
		this.idproducto = idproducto;
		this.tipoproducto = tipoproducto;
		this.marca = marca;
		this.nombre = nombre;
		this.modelo = modelo;
		this.serie = serie;
		this.descripcion = descripcion;
		this.calificacion = calificacion;
		this.likes = likes;
		this.preciominimo = preciominimo;
		this.stock = stock;
		this.fechapublicacion = fechapublicacion;
		this.alto = alto;
		this.ancho = ancho;
		this.profundidad = profundidad;
		this.peso = peso;
		this.pesoenvio = pesoenvio;
		this.envio = envio;
	}

	public Producto(int idproducto, Tipoproducto tipoproducto, Marca marca,
			String nombre, String modelo, String serie, String descripcion,
			short calificacion, int likes, double preciominimo, short stock,
			Date fechapublicacion, BigDecimal alto, BigDecimal ancho,
			BigDecimal profundidad, BigDecimal peso, BigDecimal pesoenvio,
			String envio, Set<?> productoTamanios, Set<?> productorelacionados,
			Set<?> productoMaterials, Set<?> productoCondicions,
			Set<?> revisionproductos, Set<?> listadeseoProductos,
			Set<?> descripcionproductos, Set<?> productoProveedors,
			Set<?> carritocompras, Set<?> imagenproductos,
			Set<?> detalletecnicoproductos, Set<?> caracteristicasproductos,
			Set<?> productoColors) {
		this.idproducto = idproducto;
		this.tipoproducto = tipoproducto;
		this.marca = marca;
		this.nombre = nombre;
		this.modelo = modelo;
		this.serie = serie;
		this.descripcion = descripcion;
		this.calificacion = calificacion;
		this.likes = likes;
		this.preciominimo = preciominimo;
		this.stock = stock;
		this.fechapublicacion = fechapublicacion;
		this.alto = alto;
		this.ancho = ancho;
		this.profundidad = profundidad;
		this.peso = peso;
		this.pesoenvio = pesoenvio;
		this.envio = envio;
		this.productoTamanios = productoTamanios;
		this.productorelacionados = productorelacionados;
		this.productoMaterials = productoMaterials;
		this.productoCondicions = productoCondicions;
		this.revisionproductos = revisionproductos;
		this.listadeseoProductos = listadeseoProductos;
		this.descripcionproductos = descripcionproductos;
		this.productoProveedors = productoProveedors;
		this.carritocompras = carritocompras;
		this.imagenproductos = imagenproductos;
		this.detalletecnicoproductos = detalletecnicoproductos;
		this.caracteristicasproductos = caracteristicasproductos;
		this.productoColors = productoColors;
	}

	@Id
	@Column(name = "idproducto", unique = true, nullable = false)
	public int getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(int idproducto) {
		this.idproducto = idproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipoproducto", nullable = false)
	public Tipoproducto getTipoproducto() {
		return this.tipoproducto;
	}

	public void setTipoproducto(Tipoproducto tipoproducto) {
		this.tipoproducto = tipoproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmarca", nullable = false)
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "modelo", nullable = false, length = 20)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "serie", nullable = false, length = 20)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "descripcion", nullable = false, length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "calificacion", nullable = false)
	public short getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(short calificacion) {
		this.calificacion = calificacion;
	}

	@Column(name = "likes", nullable = false)
	public int getLikes() {
		return this.likes;
	}

	public void setLikes(int likes) {
		this.likes = likes;
	}

	@Column(name = "preciominimo", nullable = false, scale = 0)
	public double getPreciominimo() {
		return this.preciominimo;
	}

	public void setPreciominimo(double preciominimo) {
		this.preciominimo = preciominimo;
	}

	@Column(name = "stock", nullable = false)
	public short getStock() {
		return this.stock;
	}

	public void setStock(short stock) {
		this.stock = stock;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechapublicacion", nullable = false, length = 13)
	public Date getFechapublicacion() {
		return this.fechapublicacion;
	}

	public void setFechapublicacion(Date fechapublicacion) {
		this.fechapublicacion = fechapublicacion;
	}

	@Column(name = "alto", nullable = false, precision = 10, scale = 4)
	public BigDecimal getAlto() {
		return this.alto;
	}

	public void setAlto(BigDecimal alto) {
		this.alto = alto;
	}

	@Column(name = "ancho", nullable = false, precision = 10, scale = 4)
	public BigDecimal getAncho() {
		return this.ancho;
	}

	public void setAncho(BigDecimal ancho) {
		this.ancho = ancho;
	}

	@Column(name = "profundidad", nullable = false, precision = 10, scale = 4)
	public BigDecimal getProfundidad() {
		return this.profundidad;
	}

	public void setProfundidad(BigDecimal profundidad) {
		this.profundidad = profundidad;
	}

	@Column(name = "peso", nullable = false, precision = 10, scale = 4)
	public BigDecimal getPeso() {
		return this.peso;
	}

	public void setPeso(BigDecimal peso) {
		this.peso = peso;
	}

	@Column(name = "pesoenvio", nullable = false, precision = 10, scale = 4)
	public BigDecimal getPesoenvio() {
		return this.pesoenvio;
	}

	public void setPesoenvio(BigDecimal pesoenvio) {
		this.pesoenvio = pesoenvio;
	}

	@Column(name = "envio", nullable = false, length = 200)
	public String getEnvio() {
		return this.envio;
	}

	public void setEnvio(String envio) {
		this.envio = envio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getProductoTamanios() {
		return this.productoTamanios;
	}

	public void setProductoTamanios(Set<?> productoTamanios) {
		this.productoTamanios = productoTamanios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getProductorelacionados() {
		return this.productorelacionados;
	}

	public void setProductorelacionados(Set<?> productorelacionados) {
		this.productorelacionados = productorelacionados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getProductoMaterials() {
		return this.productoMaterials;
	}

	public void setProductoMaterials(Set<?> productoMaterials) {
		this.productoMaterials = productoMaterials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getProductoCondicions() {
		return this.productoCondicions;
	}

	public void setProductoCondicions(Set<?> productoCondicions) {
		this.productoCondicions = productoCondicions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getRevisionproductos() {
		return this.revisionproductos;
	}

	public void setRevisionproductos(Set<?> revisionproductos) {
		this.revisionproductos = revisionproductos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getListadeseoProductos() {
		return this.listadeseoProductos;
	}

	public void setListadeseoProductos(Set<?> listadeseoProductos) {
		this.listadeseoProductos = listadeseoProductos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getDescripcionproductos() {
		return this.descripcionproductos;
	}

	public void setDescripcionproductos(Set<?> descripcionproductos) {
		this.descripcionproductos = descripcionproductos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getProductoProveedors() {
		return this.productoProveedors;
	}

	public void setProductoProveedors(Set<?> productoProveedors) {
		this.productoProveedors = productoProveedors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getCarritocompras() {
		return this.carritocompras;
	}

	public void setCarritocompras(Set<?> carritocompras) {
		this.carritocompras = carritocompras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getImagenproductos() {
		return this.imagenproductos;
	}

	public void setImagenproductos(Set<?> imagenproductos) {
		this.imagenproductos = imagenproductos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getDetalletecnicoproductos() {
		return this.detalletecnicoproductos;
	}

	public void setDetalletecnicoproductos(Set<?> detalletecnicoproductos) {
		this.detalletecnicoproductos = detalletecnicoproductos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getCaracteristicasproductos() {
		return this.caracteristicasproductos;
	}

	public void setCaracteristicasproductos(Set<?> caracteristicasproductos) {
		this.caracteristicasproductos = caracteristicasproductos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<?> getProductoColors() {
		return this.productoColors;
	}

	public void setProductoColors(Set<?> productoColors) {
		this.productoColors = productoColors;
	}

}
