package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProductoCondicion generated by hbm2java
 */
@Entity
@Table(name = "producto_condicion", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = {
		"idproducto", "idcondicion" }))
public class ProductoCondicion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9184735782387384514L;
	private int idproductoCondicion;
	private Producto producto;
	private Condicion condicion;
	private short stock;

	public ProductoCondicion() {
	}

	public ProductoCondicion(int idproductoCondicion, Producto producto,
			Condicion condicion, short stock) {
		this.idproductoCondicion = idproductoCondicion;
		this.producto = producto;
		this.condicion = condicion;
		this.stock = stock;
	}

	@Id
	@Column(name = "idproducto_condicion", unique = true, nullable = false)
	public int getIdproductoCondicion() {
		return this.idproductoCondicion;
	}

	public void setIdproductoCondicion(int idproductoCondicion) {
		this.idproductoCondicion = idproductoCondicion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcondicion", nullable = false)
	public Condicion getCondicion() {
		return this.condicion;
	}

	public void setCondicion(Condicion condicion) {
		this.condicion = condicion;
	}

	@Column(name = "stock", nullable = false)
	public short getStock() {
		return this.stock;
	}

	public void setStock(short stock) {
		this.stock = stock;
	}

}
