package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProductoTamanio generated by hbm2java
 */
@Entity
@Table(name = "producto_tamanio", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = {
		"idproducto", "idtamanio" }))
public class ProductoTamanio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3444620659835072121L;
	private int idproductoTamanio;
	private Tamanio tamanio;
	private Producto producto;
	private short stock;

	public ProductoTamanio() {
	}

	public ProductoTamanio(int idproductoTamanio, Tamanio tamanio,
			Producto producto, short stock) {
		this.idproductoTamanio = idproductoTamanio;
		this.tamanio = tamanio;
		this.producto = producto;
		this.stock = stock;
	}

	@Id
	@Column(name = "idproducto_tamanio", unique = true, nullable = false)
	public int getIdproductoTamanio() {
		return this.idproductoTamanio;
	}

	public void setIdproductoTamanio(int idproductoTamanio) {
		this.idproductoTamanio = idproductoTamanio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtamanio", nullable = false)
	public Tamanio getTamanio() {
		return this.tamanio;
	}

	public void setTamanio(Tamanio tamanio) {
		this.tamanio = tamanio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "stock", nullable = false)
	public short getStock() {
		return this.stock;
	}

	public void setStock(short stock) {
		this.stock = stock;
	}

}
