package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productorelacionado generated by hbm2java
 */
@Entity
@Table(name = "productorelacionado", schema = "web")
public class Productorelacionado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7576097473628175240L;
	private int idproductorelacionado;
	private Producto producto;
	private boolean esaccesorio;

	public Productorelacionado() {
	}

	public Productorelacionado(int idproductorelacionado, Producto producto,
			boolean esaccesorio) {
		this.idproductorelacionado = idproductorelacionado;
		this.producto = producto;
		this.esaccesorio = esaccesorio;
	}

	@Id
	@Column(name = "idproductorelacionado", unique = true, nullable = false)
	public int getIdproductorelacionado() {
		return this.idproductorelacionado;
	}

	public void setIdproductorelacionado(int idproductorelacionado) {
		this.idproductorelacionado = idproductorelacionado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "esaccesorio", nullable = false)
	public boolean isEsaccesorio() {
		return this.esaccesorio;
	}

	public void setEsaccesorio(boolean esaccesorio) {
		this.esaccesorio = esaccesorio;
	}

}
