package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProductoMaterial generated by hbm2java
 */
@Entity
@Table(name = "producto_material", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = {
		"idproducto", "idmaterial" }))
public class ProductoMaterial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1753662365192061232L;
	private int idproductoMaterial;
	private Material material;
	private Producto producto;
	private short stock;

	public ProductoMaterial() {
	}

	public ProductoMaterial(int idproductoMaterial, Material material,
			Producto producto, short stock) {
		this.idproductoMaterial = idproductoMaterial;
		this.material = material;
		this.producto = producto;
		this.stock = stock;
	}

	@Id
	@Column(name = "idproducto_material", unique = true, nullable = false)
	public int getIdproductoMaterial() {
		return this.idproductoMaterial;
	}

	public void setIdproductoMaterial(int idproductoMaterial) {
		this.idproductoMaterial = idproductoMaterial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmaterial", nullable = false)
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "stock", nullable = false)
	public short getStock() {
		return this.stock;
	}

	public void setStock(short stock) {
		this.stock = stock;
	}

}
