package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name = "proveedor", schema = "web")
public class Proveedor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5944419315452139595L;
	private int idproveedor;
	private Banco banco;
	private char tipocuenta;
	private String numerocuenta;
	private int autsrifactura;
	private String numerofactura;
	private Set<?> envios = new HashSet<Object>(0);
	private Set<?> empresas = new HashSet<Object>(0);
	private Set<?> personas = new HashSet<Object>(0);
	private Set<?> productoProveedors = new HashSet<Object>(0);
	private Set<?> facturas = new HashSet<Object>(0);
	private Set<?> revisionproveedors = new HashSet<Object>(0);

	public Proveedor() {
	}

	public Proveedor(int idproveedor, Banco banco, char tipocuenta,
			String numerocuenta, int autsrifactura, String numerofactura) {
		this.idproveedor = idproveedor;
		this.banco = banco;
		this.tipocuenta = tipocuenta;
		this.numerocuenta = numerocuenta;
		this.autsrifactura = autsrifactura;
		this.numerofactura = numerofactura;
	}

	public Proveedor(int idproveedor, Banco banco, char tipocuenta,
			String numerocuenta, int autsrifactura, String numerofactura,
			Set<?> envios, Set<?> empresas, Set<?> personas, Set<?> productoProveedors,
			Set<?> facturas, Set<?> revisionproveedors) {
		this.idproveedor = idproveedor;
		this.banco = banco;
		this.tipocuenta = tipocuenta;
		this.numerocuenta = numerocuenta;
		this.autsrifactura = autsrifactura;
		this.numerofactura = numerofactura;
		this.envios = envios;
		this.empresas = empresas;
		this.personas = personas;
		this.productoProveedors = productoProveedors;
		this.facturas = facturas;
		this.revisionproveedors = revisionproveedors;
	}

	@Id
	@Column(name = "idproveedor", unique = true, nullable = false)
	public int getIdproveedor() {
		return this.idproveedor;
	}

	public void setIdproveedor(int idproveedor) {
		this.idproveedor = idproveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbanco", nullable = false)
	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	@Column(name = "tipocuenta", nullable = false, length = 1)
	public char getTipocuenta() {
		return this.tipocuenta;
	}

	public void setTipocuenta(char tipocuenta) {
		this.tipocuenta = tipocuenta;
	}

	@Column(name = "numerocuenta", nullable = false, length = 15)
	public String getNumerocuenta() {
		return this.numerocuenta;
	}

	public void setNumerocuenta(String numerocuenta) {
		this.numerocuenta = numerocuenta;
	}

	@Column(name = "autsrifactura", nullable = false)
	public int getAutsrifactura() {
		return this.autsrifactura;
	}

	public void setAutsrifactura(int autsrifactura) {
		this.autsrifactura = autsrifactura;
	}

	@Column(name = "numerofactura", nullable = false, length = 10)
	public String getNumerofactura() {
		return this.numerofactura;
	}

	public void setNumerofactura(String numerofactura) {
		this.numerofactura = numerofactura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<?> getEnvios() {
		return this.envios;
	}

	public void setEnvios(Set<?> envios) {
		this.envios = envios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<?> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<?> empresas) {
		this.empresas = empresas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<?> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<?> personas) {
		this.personas = personas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<?> getProductoProveedors() {
		return this.productoProveedors;
	}

	public void setProductoProveedors(Set<?> productoProveedors) {
		this.productoProveedors = productoProveedors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<?> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<?> facturas) {
		this.facturas = facturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<?> getRevisionproveedors() {
		return this.revisionproveedors;
	}

	public void setRevisionproveedors(Set<?> revisionproveedors) {
		this.revisionproveedors = revisionproveedors;
	}

}
