package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Revisionproveedor generated by hbm2java
 */
@Entity
@Table(name = "revisionproveedor", schema = "web")
public class Revisionproveedor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7243772053209976063L;
	private int idrevisionproveedor;
	private Proveedor proveedor;
	private Cliente cliente;
	private short calificacion;
	private String titulo;
	private boolean etiquetarcompra;
	private String descripcion;

	public Revisionproveedor() {
	}

	public Revisionproveedor(int idrevisionproveedor, Proveedor proveedor,
			short calificacion, boolean etiquetarcompra) {
		this.idrevisionproveedor = idrevisionproveedor;
		this.proveedor = proveedor;
		this.calificacion = calificacion;
		this.etiquetarcompra = etiquetarcompra;
	}

	public Revisionproveedor(int idrevisionproveedor, Proveedor proveedor,
			Cliente cliente, short calificacion, String titulo,
			boolean etiquetarcompra, String descripcion) {
		this.idrevisionproveedor = idrevisionproveedor;
		this.proveedor = proveedor;
		this.cliente = cliente;
		this.calificacion = calificacion;
		this.titulo = titulo;
		this.etiquetarcompra = etiquetarcompra;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "idrevisionproveedor", unique = true, nullable = false)
	public int getIdrevisionproveedor() {
		return this.idrevisionproveedor;
	}

	public void setIdrevisionproveedor(int idrevisionproveedor) {
		this.idrevisionproveedor = idrevisionproveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproveedor", nullable = false)
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "calificacion", nullable = false)
	public short getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(short calificacion) {
		this.calificacion = calificacion;
	}

	@Column(name = "titulo", length = 50)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "etiquetarcompra", nullable = false)
	public boolean isEtiquetarcompra() {
		return this.etiquetarcompra;
	}

	public void setEtiquetarcompra(boolean etiquetarcompra) {
		this.etiquetarcompra = etiquetarcompra;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
