package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Revisionproducto generated by hbm2java
 */
@Entity
@Table(name = "revisionproducto", schema = "web")
public class Revisionproducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5278249260606215532L;
	private int idrevisionproducto;
	private Producto producto;
	private Cliente cliente;
	private short calificacion;
	private String titulo;
	private boolean etiquetarcompra;
	private String descripcion;

	public Revisionproducto() {
	}

	public Revisionproducto(int idrevisionproducto, Producto producto,
			short calificacion, boolean etiquetarcompra) {
		this.idrevisionproducto = idrevisionproducto;
		this.producto = producto;
		this.calificacion = calificacion;
		this.etiquetarcompra = etiquetarcompra;
	}

	public Revisionproducto(int idrevisionproducto, Producto producto,
			Cliente cliente, short calificacion, String titulo,
			boolean etiquetarcompra, String descripcion) {
		this.idrevisionproducto = idrevisionproducto;
		this.producto = producto;
		this.cliente = cliente;
		this.calificacion = calificacion;
		this.titulo = titulo;
		this.etiquetarcompra = etiquetarcompra;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "idrevisionproducto", unique = true, nullable = false)
	public int getIdrevisionproducto() {
		return this.idrevisionproducto;
	}

	public void setIdrevisionproducto(int idrevisionproducto) {
		this.idrevisionproducto = idrevisionproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "calificacion", nullable = false)
	public short getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(short calificacion) {
		this.calificacion = calificacion;
	}

	@Column(name = "titulo", length = 50)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "etiquetarcompra", nullable = false)
	public boolean isEtiquetarcompra() {
		return this.etiquetarcompra;
	}

	public void setEtiquetarcompra(boolean etiquetarcompra) {
		this.etiquetarcompra = etiquetarcompra;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
