package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Statusfactura generated by hbm2java
 */
@Entity
@Table(name = "statusfactura", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Statusfactura implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4578496993647243818L;
	private int idstatusfactura;
	private String codigo;
	private String descripcion;
	private Set<?> facturas = new HashSet<Object>(0);
	private Set<?> facturaStatusfacturas = new HashSet<Object>(0);

	public Statusfactura() {
	}

	public Statusfactura(int idstatusfactura, String codigo) {
		this.idstatusfactura = idstatusfactura;
		this.codigo = codigo;
	}

	public Statusfactura(int idstatusfactura, String codigo,
			String descripcion, Set<?> facturas, Set<?> facturaStatusfacturas) {
		this.idstatusfactura = idstatusfactura;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.facturas = facturas;
		this.facturaStatusfacturas = facturaStatusfacturas;
	}

	@Id
	@Column(name = "idstatusfactura", unique = true, nullable = false)
	public int getIdstatusfactura() {
		return this.idstatusfactura;
	}

	public void setIdstatusfactura(int idstatusfactura) {
		this.idstatusfactura = idstatusfactura;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusfactura")
	public Set<?> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<?> facturas) {
		this.facturas = facturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusfactura")
	public Set<?> getFacturaStatusfacturas() {
		return this.facturaStatusfacturas;
	}

	public void setFacturaStatusfacturas(Set<?> facturaStatusfacturas) {
		this.facturaStatusfacturas = facturaStatusfacturas;
	}

}
