package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Statuspago generated by hbm2java
 */
@Entity
@Table(name = "statuspago", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Statuspago implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4262876634399957132L;
	private int idstatuspago;
	private String codigo;
	private String descripcion;
	private Set<?> pagos = new HashSet<Object>(0);
	private Set<?> pagoStatuspagos = new HashSet<Object>(0);

	public Statuspago() {
	}

	public Statuspago(int idstatuspago, String codigo) {
		this.idstatuspago = idstatuspago;
		this.codigo = codigo;
	}

	public Statuspago(int idstatuspago, String codigo, String descripcion,
			Set<?> pagos, Set<?> pagoStatuspagos) {
		this.idstatuspago = idstatuspago;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.pagos = pagos;
		this.pagoStatuspagos = pagoStatuspagos;
	}

	@Id
	@Column(name = "idstatuspago", unique = true, nullable = false)
	public int getIdstatuspago() {
		return this.idstatuspago;
	}

	public void setIdstatuspago(int idstatuspago) {
		this.idstatuspago = idstatuspago;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statuspago")
	public Set<?> getPagos() {
		return this.pagos;
	}

	public void setPagos(Set<?> pagos) {
		this.pagos = pagos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statuspago")
	public Set<?> getPagoStatuspagos() {
		return this.pagoStatuspagos;
	}

	public void setPagoStatuspagos(Set<?> pagoStatuspagos) {
		this.pagoStatuspagos = pagoStatuspagos;
	}

}
