package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Statusdetalleenvio generated by hbm2java
 */
@Entity
@Table(name = "statusdetalleenvio", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Statusdetalleenvio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7373362089697170571L;
	private int idstatusdetalleenvio;
	private String codigo;
	private String descripcion;

	public Statusdetalleenvio() {
	}

	public Statusdetalleenvio(int idstatusdetalleenvio, String codigo) {
		this.idstatusdetalleenvio = idstatusdetalleenvio;
		this.codigo = codigo;
	}

	public Statusdetalleenvio(int idstatusdetalleenvio, String codigo,
			String descripcion) {
		this.idstatusdetalleenvio = idstatusdetalleenvio;
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "idstatusdetalleenvio", unique = true, nullable = false)
	public int getIdstatusdetalleenvio() {
		return this.idstatusdetalleenvio;
	}

	public void setIdstatusdetalleenvio(int idstatusdetalleenvio) {
		this.idstatusdetalleenvio = idstatusdetalleenvio;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
