package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Statusdetallepedido generated by hbm2java
 */
@Entity
@Table(name = "statusdetallepedido", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Statusdetallepedido implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7561717503525076207L;
	private int idstatusdetallepedido;
	private String codigo;
	private String descripcion;
	private Set<?> detallepedidos = new HashSet<Object>(0);
	private Set<?> detalleenvios = new HashSet<Object>(0);

	public Statusdetallepedido() {
	}

	public Statusdetallepedido(int idstatusdetallepedido, String codigo) {
		this.idstatusdetallepedido = idstatusdetallepedido;
		this.codigo = codigo;
	}

	public Statusdetallepedido(int idstatusdetallepedido, String codigo,
			String descripcion, Set<?> detallepedidos, Set<?> detalleenvios) {
		this.idstatusdetallepedido = idstatusdetallepedido;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.detallepedidos = detallepedidos;
		this.detalleenvios = detalleenvios;
	}

	@Id
	@Column(name = "idstatusdetallepedido", unique = true, nullable = false)
	public int getIdstatusdetallepedido() {
		return this.idstatusdetallepedido;
	}

	public void setIdstatusdetallepedido(int idstatusdetallepedido) {
		this.idstatusdetallepedido = idstatusdetallepedido;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusdetallepedido")
	public Set<?> getDetallepedidos() {
		return this.detallepedidos;
	}

	public void setDetallepedidos(Set<?> detallepedidos) {
		this.detallepedidos = detallepedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusdetallepedido")
	public Set<?> getDetalleenvios() {
		return this.detalleenvios;
	}

	public void setDetalleenvios(Set<?> detalleenvios) {
		this.detalleenvios = detalleenvios;
	}

}
