package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tamanio generated by hbm2java
 */
@Entity
@Table(name = "tamanio", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Tamanio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2977747682391344323L;
	private int idtamanio;
	private String codigo;
	private String descripcion;
	private Set<?> productoTamanios = new HashSet<Object>(0);

	public Tamanio() {
	}

	public Tamanio(int idtamanio, String codigo) {
		this.idtamanio = idtamanio;
		this.codigo = codigo;
	}

	public Tamanio(int idtamanio, String codigo, String descripcion,
			Set<?> productoTamanios) {
		this.idtamanio = idtamanio;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.productoTamanios = productoTamanios;
	}

	@Id
	@Column(name = "idtamanio", unique = true, nullable = false)
	public int getIdtamanio() {
		return this.idtamanio;
	}

	public void setIdtamanio(int idtamanio) {
		this.idtamanio = idtamanio;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tamanio")
	public Set<?> getProductoTamanios() {
		return this.productoTamanios;
	}

	public void setProductoTamanios(Set<?> productoTamanios) {
		this.productoTamanios = productoTamanios;
	}

}
