package com.web.deckshop.pojo.annotations;

// Generated 05/07/2012 04:39:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tipotransaccion generated by hbm2java
 */
@Entity
@Table(name = "tipotransaccion", schema = "web", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Tipotransaccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5805465835657978687L;
	private int idtipotransaccion;
	private String codigo;
	private String descripcion;
	private Set<?> transaccioncontables = new HashSet<Object>(0);

	public Tipotransaccion() {
	}

	public Tipotransaccion(int idtipotransaccion, String codigo) {
		this.idtipotransaccion = idtipotransaccion;
		this.codigo = codigo;
	}

	public Tipotransaccion(int idtipotransaccion, String codigo,
			String descripcion, Set<?> transaccioncontables) {
		this.idtipotransaccion = idtipotransaccion;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.transaccioncontables = transaccioncontables;
	}

	@Id
	@Column(name = "idtipotransaccion", unique = true, nullable = false)
	public int getIdtipotransaccion() {
		return this.idtipotransaccion;
	}

	public void setIdtipotransaccion(int idtipotransaccion) {
		this.idtipotransaccion = idtipotransaccion;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipotransaccion")
	public Set<?> getTransaccioncontables() {
		return this.transaccioncontables;
	}

	public void setTransaccioncontables(Set<?> transaccioncontables) {
		this.transaccioncontables = transaccioncontables;
	}

}
